### PR TITLE
fix completion when update is available (issues/475)

### LINKED ISSUE #475: Completion command does not work when an update is available
Hello,

The completion command does not work when an update is available because the update modifies the bash script

image

### PR DESCRIPTION
**Pull request by arnolem**
fix #475

### CODE REVIEW

File: src/Listener/UpdateCastorListener.php [hunk 1]
```diff
@@ -46,7 +46,7 @@ public function checkUpdate(ConsoleCommandEvent $event): void
         if (!$command) {
             return;
         }
-        if ('_complete' === $command->getName()) {
+        if ('completion' === $command->getName()) {
```
Comment (pyrech) [inline src/Listener/UpdateCastorListener.php:49]: Both command should be checked then (`completion` is the autocomplete installation script and `_complete` is the command internally called to provide suggestions according to the current input)

**Review by pyrech — CHANGES_REQUESTED** [review]

**Review by pyrech — APPROVED** [review]
I squashed your PR, fixed CS and added a note on the Changelog. Thanks :slightly_smiling_face:
