### PR TITLE
Fix import with Windows path

### LINKED ISSUE #371: Import does not work on windows
image

```
Z:\>php bin/castor -v

In castor.php line 8:

  [InvalidArgumentException]
  Could not import "examples" in "Z:\castor.php" on line 8. Reason: The import path must be formatted like this: "Z://<organization>/<repository>".


Exception trace:
  at Z:\castor.php:8
 Castor\Import\Importer->createImportException() at Z:\src\Import\Importer.php:43
 Castor\Import\Importer->import() at Z:\src\functions.php:643
 Castor\import() at Z:\castor.php:8
 require_once() at Z:\src\functions-internal.php:18
 Castor\castor_require() at Z:\src\FunctionFinder.php:91
 Castor\FunctionFinder->doFindFunctions() at Z:\src\FunctionFinder.php:42
 Castor\FunctionFinder->findFunctions() at Z:\src\Console\Application.php:183
 Castor\Console\Application->initializeApplication() at Z:\src\Console\Application.php:136
 Castor\Console\Application->doRun() at Z:\vendor\symfony\console\Application.php:175
 Symfony\Component\Console\Application->run() at Z:\bin\castor:14

In PackageImporter.php line 43:

  [Castor\Import\Exception\InvalidImportFormat]
  The import path must be formatted like this: "Z://<organization>/<repository>".


Exception trace:
  at Z:\src\Import\Remote\PackageImporter.php:43
 Castor\Import\Remote\PackageImporter->importPackage() at Z:\src\Import\Importer.php:32
 Castor\Import\Importer->import() at Z:\src\functions.php:643
 Castor\import() at Z:\castor.php:8
 require_once() at Z:\src\functions-internal.php:18
 Castor\castor_require() at Z:\src\FunctionFinder.php:91
 Castor\FunctionFinder->doFindFunctions() at Z:\src\FunctionFinder.php:42
 Castor\FunctionFinder->findFunctions() at Z:\src\Console\Application.php:183
 Castor\Console\Application->initializeApplication() at Z:\src\Console\Application.php:136
 Castor\Console\Application->doRun() at Z:\vendor\symfony\console\Application.php:175
 Symfony\Component\Console\Application->run() at Z:\bin\castor:14
```

### PR DESCRIPTION
**Pull request by pyrech**
Fix #371

### CODE REVIEW

File: src/Import/Importer.php [hunk 1]
```diff
@@ -25,6 +26,10 @@ public function import(string $path, ?string $file = null, ?string $version = nu
     {
         $scheme = parse_url($path, \PHP_URL_SCHEME);
 
+        if ($scheme && preg_match('@\w+:\\.*@', $path) && OsHelper::isWindows()) {
```
Comment (lyrixx) [inline src/Import/Importer.php:29]: Could you check for Windows first?

**Review by lyrixx — APPROVED** [review]
I would have put a comment but that's okay

**Comment by lyrixx** [comment]
Thanks
